runtime: nodejs16

env_variables:
  # --REQUIRED--
  MORALIS_API_KEY: replace_me
  APPLICATION_ID: replace_me
  MASTER_KEY: replace_me
  SERVER_URL: https://PROJECT_ID.REGION_ID.r.appspot.com:8080/server
  DATABASE_URI: mongodb://localhost:27017
  REDIS_CONNECTION_STRING: redis://127.0.0.1:6379
  RATE_LIMIT_TTL: 30
  RATE_LIMIT_AUTHENTICATED: 50
  RATE_LIMIT_ANONYMOUS: 20
  CLOUD_PATH: ./build/cloud/main.js
  
  # --OPTIONAL--
  # USE_STREAMS: false
  # STREAMS_WEBHOOK_URL: /streams-webhook